// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_KSR4112022_CF_2.Models;

#nullable disable

namespace WebAPI_KSR4112022_CF_2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230103111908_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("WebAPI_KSR4112022_CF_2.Models.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameGood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("WebAPI_KSR4112022_CF_2.Models.Goodincome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdGood")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameGood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameStock")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Goodincomes");
                });

            modelBuilder.Entity("WebAPI_KSR4112022_CF_2.Models.Goodmove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameStockFrom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameStockTowhere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Goodmoves");
                });

            modelBuilder.Entity("WebAPI_KSR4112022_CF_2.Models.Goodrest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameGood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameStock")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Goodrests");
                });

            modelBuilder.Entity("WebAPI_KSR4112022_CF_2.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameStock")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
